### PR TITLE
MX-1169 Show native M2 checkout button under some condition

### PR DESCRIPTION
**Pull request by vitaliyreznikov**
Fixes: [MX-1169]

#changelog MX-1169 Espresso parts: show native M2 checkout button under some condition

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Jira ticket link and provided a changelog message.

[MX-1169]: https://boltpay.atlassian.net/browse/MX-1169

### CODE REVIEW

**Comment by danac-gs** [comment]
I have no access to https://boltpay.atlassian.net/browse/MX-1169.
Please add more context to PR description.

**Comment by vitaliyreznikov** [comment]
@danac-gs moved to M2 project: https://boltpay.atlassian.net/browse/M2P-98

**Comment by usmanismail-bolt** [comment]
> I don't understand the reason to have customized code for one merchant be a part of our generic plugin.
> Seems wrong, but I may be wrong. Can you explain?

It makes sure all code is testable in automated testing with every release. 
Allows us to keep updating custom merchants as well.
In future we can try to make customizations more generic if possible.

**Comment by vitaliyreznikov** [comment]
@matt-thomason updated

**Comment by danac-gs** [comment]
> > I don't understand the reason to have customized code for one merchant be a part of our generic plugin.
> > Seems wrong, but I may be wrong. Can you explain?
> 
> It makes sure all code is testable in automated testing with every release.
> Allows us to keep updating custom merchants as well.
> In future we can try to make customizations more generic if possible.

We always make customizations generic if possible. At least we used to. Sometimes it is not. If they are generic we don't need merchant names in the code base, store configuration etc. Some customizations will be mutually exclusive or at least very hard and complicated to implement together. It will bloat the code base and make it unmaintainable, quite the opposite of what we want to achieve. I don't agree with this approach. It needs to be revisited.
@matt-thomason @njfaries @vitaliyreznikov @johnmccombs1 @mccottry what are your thoughts on this?

**Comment by mccottry** [comment]
@danac-gs @matt-thomason @njfaries @vitaliyreznikov @johnmccombs1 @usmanismail-bolt 
Here are a few thoughts on this PR.

1.)  **The phrase "Proceed to Terms Payment" comes across to me as awkward.**
https://github.com/BoltApp/bolt-magento2/blob/9297a3599f0e674e6c0a80a2a7abf93b87e0b1b7/view/frontend/templates/js/replacejs.phtml#L1102
For a Bolt release, it should not have made it past review without question.  At a minimum, it should be revised.  Perhaps we are wanting to say "Proceed to Payment Terms" or "See Terms of Payment" or "Review Payment Terms"

2.) **If I am interpreting the code correctly, what we are doing is creating a custom label on a button that will forward the user to the  one-page-checkout page, where Bolt is not properly supported.**
https://github.com/BoltApp/bolt-magento2/blob/9297a3599f0e674e6c0a80a2a7abf93b87e0b1b7/view/frontend/templates/js/replacejs.phtml#L1099-L1104
This does not seem like a logical addition to the code-base, especially since we are considering officially dropping support for one-page-checkout.

3.) **It is extremely unlikely that a merchant will have "Payment Terms" on the one-page-checkout page outside of the single merchant for which these changes were made.**

4.) **The hard-coded inline CSS style in the code is absolutely merchant-specific, and will not be appropriate across various themes used by other merchants.   Furthermore, with it being placed inline in the code as-is, and labeled as `!important`, it will also be very difficult to override**
https://github.com/BoltApp/bolt-magento2/blob/9297a3599f0e674e6c0a80a2a7abf93b87e0b1b7/view/frontend/templates/js/replacejs.phtml#L1101

5.) **The code has a hard-coded reference to Customer Group  = 2.  There is no way to guarantee what this customer group represents across merchants.  This very merchant-specific and inappropriate for the core code**
https://github.com/BoltApp/bolt-magento2/blob/9297a3599f0e674e6c0a80a2a7abf93b87e0b1b7/view/frontend/templates/js/replacejs.phtml#L1092

6.) **There is a reference to a custom attribute off of customer and hard-coded to a value of 414.  This is almost guaranteed to make no sense outside of the single merchant for which this code was written.**
https://github.com/BoltApp/bolt-magento2/blob/9297a3599f0e674e6c0a80a2a7abf93b87e0b1b7/view/frontend/templates/js/replacejs.phtml#L1096-L1097

7.) @danac-gs, **Instead of making a light comment, if you disagreed with the approach, it was and is your responsibility to make an explicit change request.  Had that been done, it is not likely that this code would have been merged into master.**

8.) @vitaliyreznikov, **It is likely that this PR was merged to quickly into master, bypassing a full review and perhaps ignoring the concerns of others. We have this weekly reminder in MX Weekly for a reason.
PSA: Don't ignore reviews**
https://app.asana.com/0/436430054069245/1159302772113953

-----------------------------------------------------
_My opinion is that this code is worthy of a custom extension for the merchant.  However, it has no place in our core M2 extension code as it falls short for the reasons explained in 1-6 above._

**Comment by johnmccombs1** [comment]
I agreed with @danac-gs  and @mccottry . This is a merchant-specific change and it shouldn’t be included in our core extension.

**Pull request merged**
