### PR TITLE
Do not create immutable quote for API driven integration

### PR DESCRIPTION
**Pull request by vitaliyreznikov**
- introduce feature switch M2_ENABLE_API_DRIVEN_INTEGRAION
- Under feature switch update **getCartData** function to create bolt order without immutable quote creation.

Eventually we will delete code for immutable quote so I prefer to have few <IF> statement for now rather than separate function.

Fixes: (link Jira ticket)

#changelog Do not create immutable quote for API driven integration

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by mikeshutov-bolt** [comment]
What is the purpose for having this extra feature? isRecalculateTotalForAPIDrivenIntegration im trying to understand why do we need this as a just in case feature?

**Comment by vitaliyreznikov** [comment]
> What is the purpose for having this extra feature? isRecalculateTotalForAPIDrivenIntegration im trying to understand why do we need this as a just in case feature?

The total calculation is very heavy function. From my understanding, we do not need it because the total should be calculated before when a quote is updated for whatever reasons.
But I may be wrong, so I added feature switch we can enable across the board if recalculation is needed

**Review by mikeshutov-bolt — APPROVED** [review]
Not a fan of the isRecalculateTotalForAPIDrivenIntegration feature personally but I understand the reasoning, it just seems to add more complexity and switches.
LGTM otherwise.

**Review by dumega — DISMISSED** [review]
@vitaliyreznikov I run some tests on my local, there is an error "Bolt order doesn't contain immutable order id" (https://github.com/BoltApp/bolt-magento2/blob/5c19d973839413a913e614c14617ed57512c1d33/Helper/Cart.php#L760) when creating Bolt cart. Could you double check?

**Comment by vitaliyreznikov** [comment]
@dumega With this change, we do not expect shipping calls or ever another call should work. We already have shipping call, tax call,s and order creation in the new flow. I'll add some guide about how you can test this.

**Comment by vitaliyreznikov** [comment]
@dumega PMed some instruction, please review again

**Comment by vitaliyreznikov** [comment]
@dumega I made a fix after our offline conversation. Please take a look now.

**Comment by vitaliyreznikov** [comment]
@dumega We need some changes on bolt side which allow you to test all flow and those changes are not deployed yet.
But please let me merge this one because:
1. It works on my side
2. shipping step error you see most likely not related to this PR
3. we have enough time before release to fix any issues in following PRs if needed

**Pull request merged**
