### PR TITLE
Restaurantsupply

### PR DESCRIPTION
**Pull request by danac-gs**

### CODE REVIEW

**Comment by daisy1754** [comment]
@danac-gs 
Can you self-merge this to `temporary-merge`, remove restaurantsupply specifics, and send pull request from `temporary-merge` to `develop`?

**Comment by daisy1754** [comment]
@danac-gs hmm, this pull request is from `restaurantsupply` to `temporary-merge`. I want from `temporary-merge` to `develop`

**Comment by daisy1754** [comment]
screen shot 2018-05-24 at 1 39 20 pm

**Comment by danac-gs** [comment]
That one I have created for myself to see the diff in the browser while
doing the manual merge in the editor. Was not meant to be reviewed.

**Pull request merged**
