### PR TITLE
Use GET for OAuth redirect endpoint and add logger

### PR DESCRIPTION
**Pull request by nickfiacco-bolt**
This is so that the OAuth redirect endpoint is compliant with the OAuth spec.

# Description
Please include a summary of the change and which issue is fixed. Include the motivation for the changes, and comment on your PR if necessary for clarity.

Fixes: (link Jira ticket)

#changelog Use GET for OAuth redirect endpoint and add logger

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Review by adentong — COMMENTED** [review]
I'd rather we don't add something that's not used anywhere (in this case LogHelper)

**Comment by nickfiacco-bolt** [comment]
> I'd rather we don't add something that's not used anywhere (in this case LogHelper)

I find it pretty annoying to have to recompile when changing the inputs to the singleton. Adding the logger makes debugging way easier-- and we should always make debugging easier

**Comment by adentong** [comment]
> > I'd rather we don't add something that's not used anywhere (in this case LogHelper)
> 
> I find it pretty annoying to have to recompile when changing the inputs to the singleton. Adding the logger makes debugging way easier-- and we should always make debugging easier

What do you mean by "changing the inputs to the singleton"? In any case, whenever you actually use the LogHelper locally to debug wouldn't you have to recompile anyways?

**Comment by nickfiacco-bolt** [comment]
> > > I'd rather we don't add something that's not used anywhere (in this case LogHelper)
> > 
> > 
> > I find it pretty annoying to have to recompile when changing the inputs to the singleton. Adding the logger makes debugging way easier-- and we should always make debugging easier
> 
> What do you mean by "changing the inputs to the singleton"? In any case, whenever you actually use the LogHelper locally to debug wouldn't you have to recompile anyways?

You don't have to recompile if you don't change the params to any interfaces. You can just make the change and it is automatically picked up

**Comment by adentong** [comment]
Huh TIL

**Review by adentong — APPROVED** [review]

**Review by njfaries — APPROVED** [review]

**Pull request merged**
