### PR TITLE
Remove M2_SAVE_CART_IN_SECTIONS feature switch and related JS code

### PR DESCRIPTION
**Pull request by vitaliyreznikov**
When we started to persist bolt cart in magento section we added feature switch to return to the old approach if needed.
We had it in 2.9.0 as well in 2.9.1 and don't need to have in 2.10.0

#changelog Code refactoring

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by vitaliyreznikov** [comment]
We decided to return to the tech doc stage. I plan to work on the text tomorrow and just wanted to have clear JS to add links in doc on it.

**Comment by danac-gs** [comment]
> We decided to return to the tech doc stage. I plan to work on the text tomorrow and just wanted to have clear JS to add links in doc on it.

This PR removes the old code that we might want to stick to eventually. Perhaps you can add links to the code as is, maybe even links to 2.7.0 and 2.9.1 versions of it.

**Comment by johnmccombs1** [comment]
@vitaliyreznikov Broken unit test http://prntscr.com/t8km0m Can you fix it?

**Comment by vitaliyreznikov** [comment]
@danac-gs Ok, let's leave this open for now.

**Pull request closed without merging**
