### PR TITLE
Custom Button Attributes

### PR DESCRIPTION
**Pull request by mccottry**
# Description
There are several non-advertised "Secret Checkout Button Options" that can be applied to the Bolt checkout button.  One example is in changing the buttons text as follows:

`<div class="bolt-checkout-button" data-btn-txt="Pay now"></div>`

While we wish to provide an easy to use means to accomplish this, we also do not wish to advertise this to merchants.
https://www.notion.so/boltteam/Secret-Checkout-Button-Options-f732422101474a84a4922af3f1e0b904

To accomplish this, we can utilize our existing "Additional Configuration" field, 
https://github.com/BoltApp/bolt-magento2/blob/master/etc/adminhtml/system.xml#L220

This field holds arbitrary JSON and for custom button attributes, we will use the following format:
```
{
    "checkoutButtonAttributes": {
        "<attribute1_name>": "<attribute1_value>",
        "<attribute2_name>": "<attribute2_value>",
        "<attribute3_name>": "<attribute3_value>"
        ... 
    }
}    
```
In the example above, it would look like this:
```
{
    "checkoutButtonAttributes": { 
       "data-btn-txt": "Pay now"
     }                                  
}.
```

Fixes: https://boltpay.atlassian.net/browse/M2P-189

#changelog Custom Button Attributes

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by mccottry** [comment]
> I am OK with this approach but I think we need to discuss it more broadly.

@vitaliyreznikov What specifically is your concern?

**Comment by vitaliyreznikov** [comment]
@mccottry 
* we need to confirm we ok to use hidden settings
* we need to confirm we ok to have this code in main repo.

No concerns, just want to make sure we are on the same page

**Comment by mccottry** [comment]
> @mccottry
> 
> * we need to confirm we ok to use hidden settings
> * we need to confirm we ok to have this code in main repo.
> 
> No concerns, just want to make sure we are on the same page

@vitaliyreznikov 
> we need to confirm we ok to use hidden settings
This is required to be a hidden, non-advertised setting as explained in the description above.

_While we wish to provide an easy to use means to accomplish this, we also do not wish to advertise this to merchants._
https://www.notion.so/boltteam/Secret-Checkout-Button-Options-f732422101474a84a4922af3f1e0b904

> we need to confirm we ok to have this code in main repo.
I'm a little confused by this.  

If you mean 
_is it ok to have hidden settings in the main repo,_ 
**yes, it is already in the main repo.**

If you mean, 
_Do we want to support hidden settings in the repo?_
If no philosophy has changed since [here](https://app.asana.com/0/436430054069245/843705092435857), **then yes, we want to support hidden settings in the plugin for these type of features.**

If the question is 
_Do we want to build out per-merchant [customizations by extension](https://boltpay.atlassian.net/browse/EN-204?focusedCommentId=36388) instead of a general plugin enhancement for a known supported Bolt feature?_ 
**I believe that we have had several meetings and several mentions in MX Weekly that we are extending the core code.**

Is there a reason why you believe that this would not be useful in the core plugin code?  It is possible that I over-looked something, but, I can not think of any reason for this concern of the top of my head.

**Comment by danac-gs** [comment]
@mccottry please fix the conflicts

**Pull request merged**
