### PR TITLE
M2P-155 Bugfix - Unable to remove Amasty GiftCard

### PR DESCRIPTION
**Pull request by dumega**
# Description
```
Steps to reproduce: 

1. Purchase a gift card (generated by Amasty GiftCard)
2. Add a simple product to cart
3. Go to cart page
4. Open Bolt modal and apply the gift card in the "Delivery" or "Payment" step
5. Keep the Bolt modal open and directly reload the cart page
6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard 
7. Open the Bolt modal

Expected behavior:
The Bolt modal does not have any applied gift card

Actual behavior:
The Bolt modal still has the previous gift card
```

Root cause:
When loading the cart page, we save the current quote without giftcard into cache, also an associated cart is created on Bolt side. Then we apply giftcard through Bolt modal, the Bolt cart get updated while the cache stay the same. So when we remove the giftcard from cart page, the plugin just retrieve the cache and wont refresh the cart on Bolt side, it result in a mismatch.

Fixes: https://boltpay.atlassian.net/browse/M2P-155

#changelog Bugfix - Unable to remove Amasty GiftCard

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by dumega** [comment]
> @dumega Could we use a simpler approach - just adding something unique related to the Amasty GiftCard applied to quote (if existing, used gc balance for instance) to the cart cache identifier, checking it every time? Perhaps that way it would get solved by itself without the use of much more additional code.
> @vitaliyreznikov @matt-thomason @njfaries

@danac-gs The GiftCard is applied on Bolt modal, not on the cart page, so the cart cache identifier does not change for the same quote (cause the quote data does not change). So I am afraid your suggestion wont work.

**Comment by danac-gs** [comment]
> @danac-gs The GiftCard is applied on Bolt modal, not on the cart page, so the cart cache identifier does not change for the same quote (cause the quote data does not change). So I am afraid your suggestion wont work.

@dumega 

4. Open Bolt modal and apply the gift card in the "Delivery" or "Payment" step
_Here a call to a store endpoint is made, and some (identifier, quote related / Amasty gc) data is changed and the change stored in DB at store end_
5. Keep the Bolt modal open and directly reload the cart page
_The new cache identifier is generated (taking into account the quote state change in the previous step) and Bolt cart is updated_
6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard
_I assume the problem is here. We don't get a notification on the front end that the cart (totals) had been changed and that create cart (BoltCheckout configure with a promise) should be called again_

**This looks like another side effect of using sections the way we do, and we are still fixing the consequences instead of dealing with the root cause (for a month or so already)**

**Comment by dumega** [comment]
@danac-gs 

First lets check how we generate the cache identifier

https://github.com/BoltApp/bolt-magento2/blob/c039effea085bdeb0ba172bf7fa3bb4b0837244c/Helper/Cart.php#L581

So it always calculate the cache identifier by the cart content data, then even there are two quote with different id but same content, the cache identifier would be the same.

Then referring to https://github.com/BoltApp/bolt-magento2/blob/master/Helper/Cart.php#L725 , the plugin just return the cached Bolt order insteading calling Bolt Ceate Order API.


**4. Open Bolt modal and apply the gift card in the "Delivery" or "Payment" step**
_Here a call to a store endpoint is made, and some (identifier, quote related / Amasty gc) data is changed and the change stored in DB at store end_

Bolt order at Bolt server side also get updated cause discounts.code.apply returns discount info and new totals. **The problem is here**, the Bolt order saved in the cache at store end does not get updated, so there is mismatch.

**5. Keep the Bolt modal open and directly reload the cart page**
_The new cache identifier is generated (taking into account the quote state change in the previous step) and Bolt cart is updated_

Although a new cache identifier would be generated, the old cache identifier still exists, and the new cache identifier would associate with another Bolt order which works as expected.

**6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard**
_I assume the problem is here. We don't get a notification on the front end that the cart (totals) had been changed and that create cart (BoltCheckout configure with a promise) should be called again_

After removing GiftCard, the cart content data is as same as before, so it retrieve Bolt order from cache and never call the Bolt Ceate Order API.

**Comment by danac-gs** [comment]
https://github.com/BoltApp/bolt-magento2/blob/c039effea085bdeb0ba172bf7fa3bb4b0837244c/Helper/Cart.php#L581-L596

This method can be extended to include Amasty GiftCard / quote related addition to the cache identifier.
As it was done for custom address fields and gift message.

**Comment by dumega** [comment]
> https://github.com/BoltApp/bolt-magento2/blob/c039effea085bdeb0ba172bf7fa3bb4b0837244c/Helper/Cart.php#L581-L596
> 
> This method can be extended to include Amasty GiftCard / quote related addition to the cache identifier.
> As it was done for custom address fields and gift message.

@danac-gs There is nothing to do with cache identifier
1. Initially on the cart page we do not have GiftCard applied, so the cache identifier does not have any info with GiftCard.
2. On the Bolt modal, when we add GiftCard, the cache identifier is not updated (actually it should not get updated)
3. Then after removing the GiftCard on the cart page, the cart changes back to the previous state which has same cache identifier as before.

Besides that, if we apply the GiftCard on the cart page, the cart does have Amasty GiftCard info in the discount property, do you mean we need to add some more extra info?

**Comment by dumega** [comment]
> @dumega If I want to test this with last plugin version I should cherry-pick this one as well, correct?
> #798

@vitaliyreznikov yes, if you want to test with Amastry GiftCard v2.0.0 and later, you need to have the PR #798 included.

**Comment by danac-gs** [comment]
@dumega  I think we should do 2 things (only):

1. add extra info, quote / immutable quote / Amasty Gift Card related, to the cache identifier
2. identify and fix why the totals change (adding / removing gift cards) does not trigger cart update on the front end (shopping cart page, replacejs.phtml)

**Comment by dumega** [comment]
@danac-gs 
For the two things you suggest,
`1.  add extra info, quote / immutable quote / Amasty Gift Card related, to the cache identifier`
Again, I believe it is irreverent to this issue. And we can consider to add those extra info in another PR

`2. identify and fix why the totals change (adding / removing gift cards) does not trigger cart update on the front end (shopping cart page, replacejs.phtml)`
In the front page, the ajax get triggered to get Bolt order when removing the GiftCard, but due to the existence of cache, it returns the cache instead of calling api. And this PR is mainly to fix this issue.

**Comment by danac-gs** [comment]
> @danac-gs
> For the two things you suggest,
> `1. add extra info, quote / immutable quote / Amasty Gift Card related, to the cache identifier`
> Again, I believe it is irreverent to this issue. And we can consider to add those extra info in another PR
> 
> `2. identify and fix why the totals change (adding / removing gift cards) does not trigger cart update on the front end (shopping cart page, replacejs.phtml)`
> In the front page, the ajax get triggered to get Bolt order when removing the GiftCard, but due to the existence of cache, it returns the cache instead of calling api. And this PR is mainly to fix this issue.

@dumega As I see it, if we do 1., the cache identifier wont match in 2. and the api would be called, generating and caching a new cart, instead returning an old one from cache

**Comment by dumega** [comment]
@danac-gs Well, the rule of the cache identifier is unique identifier for same cart, right? 
The two cart
1. The one before opening the Bolt modal (step 3. Go to cart page)
2. The one after removing the gift card (step 6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard )

Do you think they are same or not?  In my opinion, they are same, even we add more extra info, but they are still same cart. Then why/how do we return different cache identifier for same cart?

**Comment by danac-gs** [comment]
> @danac-gs Well, the rule of the cache identifier is unique identifier for same cart, right?
> The two cart
> 
> 1. The one before opening the Bolt modal (step 3. Go to cart page)
> 2. The one after removing the gift card (step 6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard )
> 
> Do you think they are same or not? In my opinion, they are same, even we add more extra info, but they are still same cart. Then why/how do we return different cache identifier for same cart?

@dumega Currently they are treated the same because there's nothing to distinguish between them in the cache identifier. And they really are not the same, one has a gift cart applied and the other one does not. If we add some gift card related field to the cache identifier then they won't be treated as the same cart anymore and everything should work. I can't know if it 100% would, but it seems far simpler then this pull request so it is worth trying imho. No adding to or changing the existing plugin logic, just adding another part to the identifier (which, I admit, might be a challenge to get right).

**Comment by dumega** [comment]
> > @danac-gs Well, the rule of the cache identifier is unique identifier for same cart, right?
> > The two cart
> > 
> > 1. The one before opening the Bolt modal (step 3. Go to cart page)
> > 2. The one after removing the gift card (step 6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard )
> > 
> > Do you think they are same or not? In my opinion, they are same, even we add more extra info, but they are still same cart. Then why/how do we return different cache identifier for same cart?
> 
> @dumega Currently they are treated the same because there's nothing to distinguish between them in the cache identifier. And they really are not the same, one has a gift cart applied and the other one does not. If we add some gift card related field to the cache identifier then they won't be treated as the same cart anymore and everything should work. I can't know if it 100% would, but it seems far simpler then this pull request so it is worth trying imho. No adding to or changing the existing plugin logic, just adding another part to the identifier (which, I admit, might be a challenge to get right).

@danac-gs If one of them has gift card applied, they would definitely be different, but none of them have gift card, that's why I says they are same. 

Do you mind running some tests on your side to see how it works?

**Comment by danac-gs** [comment]
@dumega I am probably missing something, but I still think something's not right in the process and that it should be done simpler. I will try to reiterate the flow to see if I'm right or not.
1. Purchase a gift card (generated by Amasty GiftCard)
* I am assuming this is done in another order, so we have it available to use in this one
2. Add a simple product to cart
3. Go to cart page
* no cart cached yet
* the plugin collects the cart data
* the cart data has no discounts property populated
* sends it to bolt
* receives the bolt order (cart data)
* generates the cache identifier and stores the bolt order response in cache 
4. Open Bolt modal and apply the gift card in the "Delivery" or "Payment" step
* the gc code is sent to bolt
* the verify discount endpoint is called (bolt -> plugin)
* successfully applied to the quote (we need to apply it to both parent and immutable quotes)
* at this point the state of the cart has changed, but the change is not reflected yet to the underlying shopping cart page, only in checkout modal
* this means there's an update somewhere in DB that connects GC to the quote (we need to find this and use it in the cache identifier, eventually)
5. Keep the Bolt modal open and directly reload the cart page
* at some point (after the page is loaded) a call to cart/data is made
* in the process the plugin loads the quote, creates an immutable quote and generates the cache identifier
* the quote / cart now has the discounts array with one element, the gift card data
* the cache identifier should be different than previously created one because there's a gift card addition to the cart object (even with no adding new property to the cache identifier, so perhaps it is not necessary after all)
* a new cart is generated and fetched, ready to be loaded in modal eventually
6. Delete the applied gift card by clicking “Remove” button of Amasty GiftCard
* I assume this is done via an AJAX call
* when the response is received, the state of the cart (totals updated, no gift card applied) reflects on the front end, shopping cart page
* our plugin detects the change and calls Boltcheckout.configure with a cart parameter as a promise, calling cart/data again and fetches a new cart state as a resolved promise (PERHAPS THE PROBLEM IS HERE, DOES THIS CALL REALLY HAPPENS?)
* expectation is that the cached cart from the step 3. is received (the one with no GC applied)
7. Open the Bolt modal
* actually the cart has not been changed, it remains the same as in step 5.
8. _What happens when you reload the page again?_

**Conclusion**:
* It seems that I was wrong regarding the need of adding to the cache identifier.
* On the other hand, according to the usual flow and functionality (actually the old one I am familiar with, without the bolt cart in sections) this issue should not happen.

**Proposal**: 
* Try with cart caching disabled to validate or invalidate this as a caching issue 
* Verify the create cart / Boltcheckout.configure is triggered in the step 6.

Note: I will reiterate my previous comment from this thread
* _This looks like another side effect of using sections the way we do, and we are still fixing the consequences instead of dealing with the root cause (for a month or so already)_

**Comment by dumega** [comment]
@danac-gs 

> 8. What happens when you reload the page again?

The issue sill exist when you reload the page.

> 
This looks like another side effect of using sections the way we do, and we are still fixing the consequences instead of dealing with the root cause (for a month or so already)

I will verify if this issue is related to Magento sectionns

**Comment by danac-gs** [comment]
Please also try with caching disabled

**Comment by dumega** [comment]
@danac-gs I setup a fresh M2 site and install Bolt plugin v2.7.0 which does not have Magento sections, then this issue is still reproducible. So I believe this is not related to Magento sections.

**Comment by dumega** [comment]
> Please also try with caching disabled

Well, once I set **Cache Bolt Order Token (Performance Optimization)**  to No, the cart can be updated properly. so it is related to cache 

BTW also tested with v2.7.0

**Comment by danac-gs** [comment]
> > Please also try with caching disabled
> 
> Well, once I set **Cache Bolt Order Token (Performance Optimization)** to No, the cart can be updated properly. so it is related to cache
> 
> BTW also tested with v2.7.0

@dumega then I guess updating cacheIdentifier should fix it after all

**Comment by dumega** [comment]
> > > Please also try with caching disabled
> > 
> > 
> > Well, once I set **Cache Bolt Order Token (Performance Optimization)** to No, the cart can be updated properly. so it is related to cache
> > BTW also tested with v2.7.0
> 
> @dumega then I guess updating cacheIdentifier should fix it after all

@danac-gs It just double confirms this is related to cache issue, and my solution would fix it.

**Comment by danac-gs** [comment]
> > > > Please also try with caching disabled
> > > 
> > > 
> > > Well, once I set **Cache Bolt Order Token (Performance Optimization)** to No, the cart can be updated properly. so it is related to cache
> > > BTW also tested with v2.7.0
> > 
> > 
> > @dumega then I guess updating cacheIdentifier should fix it after all
> 
> @danac-gs It just double confirms this is related to cache issue, and my solution would fix it.

@dumega I am sure your solution works, I never doubted that. My point is that this is not the best solution in regard of how caching was implemented and meant to be used. It's more like a workaround.

**Comment by dumega** [comment]
> > > > > Please also try with caching disabled
> > > > 
> > > > 
> > > > Well, once I set **Cache Bolt Order Token (Performance Optimization)** to No, the cart can be updated properly. so it is related to cache
> > > > BTW also tested with v2.7.0
> > > 
> > > 
> > > @dumega then I guess updating cacheIdentifier should fix it after all
> > 
> > 
> > @danac-gs It just double confirms this is related to cache issue, and my solution would fix it.
> 
> @dumega I am sure your solution works, I never doubted that. My point is that this is not the best solution in regard of how caching was implemented and meant to be used. It's more like a workaround.

@danac-gs Yes, I know your point is to update the cacheIdentifier instead. But I have explained in the previous comment that updating cacheIdentifier wont fix this issue, cause same cart content is always related to same cacheIdentifier (I have double checked how we implement cache), especially there is not any other extended data like GiftCard in the cart. 

Or do you mean generating different cacheIdentifier for same cart content? That seems to be illogical. 

And if you insist on your idea, will you be able to give it a try on your side? Maybe I missed something, please correct me with coding.

**Comment by danac-gs** [comment]
@dumega The issue is actually more generic and affects all coupons applied through Bolt modal. What really happens is the following:

1. Create a cart without discounts. Bolt order (cart) is cached (order token).
2. Apply a discount. The cart on Bolt end tied with the order token is updated with discount info.
3. Reload the page. A new immutable quote / cart / order token is generated (with discount).
4. Remove the discount. Plugin checks for cache, there's no discount in cart and the cache identifier is identical to the first cart (1.)
5. The cached (1.) version is returned and with its order token passed to checkout modal. Checkout fetches the cart with that token from Bolt, however on Bolt end that cart has the discount (2.)

This was a bit tricky one, I had persistent and mostly wrong assumptions in my comments. Fortunately, that lead us to a good resolution and a better understanding as well as an appropriate solution.

Please check https://github.com/BoltApp/bolt-magento2/pull/833

**Comment by dumega** [comment]
> @dumega The issue is actually more generic and affects all coupons applied through Bolt modal. What really happens is the following:
> 
> 1. Create a cart without discounts. Bolt order (cart) is cached (order token).
> 2. Apply a discount. The cart on Bolt end tied with the order token is updated with discount info.
> 3. Reload the page. A new immutable quote / cart / order token is generated (with discount).
> 4. Remove the discount. Plugin checks for cache, there's no discount in cart and the cache identifier is identical to the first cart (1.)
> 5. The cached (1.) version is returned and its order token passed to checkout modal. Checkout fetches the cart with that token from Bolt, however on Bolt end that cart has the discount (2.)
> 
> This was a bit tricky one, I had persistent and mostly wrong assumptions in my comments. Fortunately, that lead us to a good resolution and a better problem understanding as well as an appropriate solution.
> 
> Please check #833

@danac-gs Finally we reach an agreement :), your description is exactly as same as I described in my previous comment, so ur solution would cover all the dicount types, right?

**Comment by danac-gs** [comment]
> @danac-gs Finally we reach an agreement :), your description is exactly as same as I described in my previous comment, so ur solution would cover all the dicount types, right?

@dumega Yes, clearing the cache by tag every time discount validation hook is called solves it in general case.

**Comment by vitaliyreznikov** [comment]
@dumega Are you ok to close this one since we are probably want to merge another one https://github.com/BoltApp/bolt-magento2/pull/806 ?

**Pull request closed without merging**
