### PR TITLE
[MA-572] Fix integration tests

### PR DESCRIPTION
**Pull request by adentong**
So https://github.com/BoltApp/bolt-magento2/pull/1133 broke our integration tests. This is because the sandbox merchant we use don't have preauth enabled. Originally I wanted to revert the PR but I decided to just set is_pre_auth to 0 in the script. Also change integration tests to run for every commit. A successful run only takes about 10 minutes, which is a not a long time.

Fixes: (link Jira ticket)

#changelog Fix integration tests

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by adentong** [comment]
@mikeshutov-bolt

**Comment by adentong** [comment]
See https://app.circleci.com/pipelines/github/BoltApp/bolt-magento2/8914/workflows/80df5a65-47f3-4261-b970-a90a391c7fc1/jobs/34090/steps for an almost successful run. The one remaining test is broken for some other reason.

**Review by vitaliyreznikov — COMMENTED** [review]
I agree we need to run integration tests more often, but after this change, if we create two commits in different PR at the same time second fail because we use one domain and one ngrok setting.
If we want to parallel test we need to have some semaphore to organize it.

**Comment by vitaliyreznikov** [comment]
I didn't know we run tests for not-pre-auth case. Should we change this down the road?

**Comment by adentong** [comment]
makes sense. i'll revert the integration test change for now then.

**Review by vitaliyreznikov — APPROVED** [review]

**Pull request merged**
