### PR TITLE
M2P-342 Fix displaying of applied discount label

### PR DESCRIPTION
**Pull request by johnmccombs1**
# Description
Fix displaying of applied discount label

Fixes: https://boltpay.atlassian.net/browse/M2P-342

#changelog M2P-342 Fix displaying of applied discount label

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by johnmccombs1** [comment]
FYI, I’m currently working on applying the merchant customization to our repo.
This PR is to apply @isklyarenko 's change in this commit https://github.com/BoltApp/bolt-magento2/commit/7209b4ee09624eeb6eac61a7ee64efb2d3efb975 to our repo

**Comment by njfaries** [comment]
How does this interact with https://github.com/BoltApp/bolt-magento2/pull/996?

**Review by danac-gs — APPROVED** [review]

**Review by vitaliyreznikov — COMMENTED** [review]
@johnmccombs1 Could you please add some explanations in which cases new code gives a different result than a new one?

**Comment by johnmccombs1** [comment]
@isklyarenko said that the problem was by the Stripe payment processor which requires level3 data.  @isklyarenko Can you test and explain it for @vitaliyreznikov @njfaries?

**Comment by vitaliyreznikov** [comment]
@johnmccombs1 I've discussed the issue with @isklyarenko and looks like we need a slightly different solution if we want to have this in the main repo. I will create PR later, thank you!
https://boltpay.atlassian.net/browse/M2P-363

**Pull request closed without merging**
