### PR TITLE
Implementation of Update Cart endpoint - Pre-step 1

### PR DESCRIPTION
**Pull request by dumega**
# Description

1. Move supports for Magento GiftCard and Unirgy GiftCert from Model/Api/DiscountCodeValidation.php to Helper/Discount.php
2. Move some embedded logic to separate functions for reuse

Next PR : https://github.com/BoltApp/bolt-magento2/pull/851

Related task https://boltpay.atlassian.net/browse/M2P-64

Fixes: (link Jira ticket)

#changelog Implementation of Update Cart endpoint - Pre-step 1

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by mccottry** [comment]
> @dumega As this is a new feature, a couple of them actually - update cart and multiple discounts application and removal, could you leave the old discount code as is (to minimize chances of backward compatibility issues) and add the new code separately, via feature switches if necessary. This way we can work on the new code independently of, and with no restrictions implicit to the old code. With the new update cart functionality in place, there is probably a lot of space for improvement and simplification of the discount code validation plugin code.
> 
> @vitaliyreznikov @matt-thomason @njfaries @johnmccombs1 @mccottry thoughts?

agreed.  This should not be a refactor, but an extension that can be switched on and off.  The benefit is that we keep current stability and at the same time allow for the new code to be rolled out and matured on a natural time frame.

**Comment by dumega** [comment]
@danac-gs @mccottry @vitaliyreznikov 

In my opinion, we can implement the PR of pre-step 1&2&3 with/without the new feature.

In this PR

> 1. Move supports for Magento GiftCard and Unirgy GiftCert from Model/Api/DiscountCodeValidation.php to Helper/Discount.php
> 2. Move some embedded logic to separate functions for reuse

Actually I do not change any logic, just refactoring.

**Comment by dumega** [comment]
> @danac-gs @mccottry I am not sure it is the best way. This PR looks like refactoring. If we do refactoring under feature switch it takes months to get rid of old code.
> 
> @dumega BTW this PR is a little hard to review. Could you explain it a little more? For example this one:
> 
> image
> 
> Do I understand correctly you just move method from one class to another? If so, could you please do it in separate PR? The separate commits in this PR is also OK for me.

@vitaliyreznikov do you mean create separate PRs for the two purposes? or even three PRs (so Magento GiftCard and Unirgy GiftCert could be separate PRs)?

> 1. Move supports for Magento GiftCard and Unirgy GiftCert from Model/Api/DiscountCodeValidation.php to Helper/Discount.php

> 2. Move some embedded logic to separate functions for reuse

**Comment by dumega** [comment]
Well, after consideration, I think I would better not touch the DiscountCodeValidation.php when implementing this new experimental feature, otherwise it seems to lead us to something irrelevant.

Will update the PRs

**Comment by johnmccombs1** [comment]
@dumega I'm seeing a lot of changes here. Can you add unit tests for them?

**Comment by dumega** [comment]
@danac-gs @mccottry @vitaliyreznikov @johnmccombs1 

I think it is reasonable to move some supports from Model/Api/DiscountCodeValidation.php to Helper/Discount.php for common reuse. Please review https://github.com/BoltApp/bolt-magento2/pull/857 and https://github.com/BoltApp/bolt-magento2/pull/858

Also I plan to abandon the rest changes in this PR, to minimize chances of backward compatibility issues.

**Comment by dumega** [comment]
> @dumega I'm seeing a lot of changes here. Can you add unit tests for them?

@johnmccombs1 I assume there will be some changes in the structure and code, so I think we can add unit tests when all the reviewers confirm the main changes

**Pull request closed without merging**
