### PR TITLE
Collect total if discount did not found

### PR DESCRIPTION
**Pull request by vitaliyreznikov**
Steps to reproduce an issue:
- set feature APIDrivenIntegrationEnabled to true (not necessary to change settings on bolt side)
- add discount to quote via Magento API
- open bolt modal

**Actual behavior:**
no discount in bolt cart

#changelog Collect total if discount did not found

### CODE REVIEW

**Review by dumega — COMMENTED** [review]
@vitaliyreznikov 
We do not get the coupon code it is because the quote in checkout session is not synced, then my proposal is change the code in https://github.com/BoltApp/bolt-magento2/blob/57623b7162dbc285a1de3d272139d1e5ce3b0eee/Helper/Cart.php#L1804
from $this->checkoutSession->getQuote() to $this->quoteRepository->getActive($quote->getId())
Then also updates the code in https://github.com/BoltApp/bolt-magento2/blob/57623b7162dbc285a1de3d272139d1e5ce3b0eee/Helper/Cart.php#L2859
from $appliedSaleRuleIds = $address->getAppliedRuleIds() to$appliedSaleRuleIds = $quote->getAppliedRuleIds()

**Comment by vitaliyreznikov** [comment]
@dumega So change for 1804 should like 
```
        if ($this->deciderHelper->isAPIDrivenIntegrationEnabled()) {
            $quote = $this->quoteRepository->getActive(
                $this->checkoutSession->getQuote()->getId()
            );
        } else {
            // If the immutable quote is passed (i.e. discount code validation, bugsnag report generation)
            // load the parent quote, otherwise load the session quote
            $quote = ($immutableQuote && $immutableQuote->getBoltParentQuoteId() != $immutableQuote->getId()) ?
                $this->getQuoteById($immutableQuote->getBoltParentQuoteId()) :
                $this->checkoutSession->getQuote();
        }
```
But I am not sure about change for line 2829.
Can I ask you to create PR with this?

**Comment by vitaliyreznikov** [comment]
Had some offline discussion with @dumega and @mikeshutov-bolt , decided to go ahead with the initial approach

**Review by mikeshutov-bolt — APPROVED** [review]
LGTM for RC1 we may improve this later on as we discussed.

**Pull request merged**
