### PR TITLE
EN-5740 Bugfix: JS error on cart page if quote is empty

### PR DESCRIPTION
**Pull request by dumega**
# Description
Use the require-specific errbacks of RequireJS tools to deal with any error if a module fails to load and log error details to console

Fixes: https://boltpay.atlassian.net/browse/EN-5740

#changelog Bugfix: JS error on cart page if quote is empty

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by danac-gs** [comment]
@dumega I have concerns what impact would this have on pages that are cached, non shopping card pages. If this block is needed somewhere, and I assume it is, we might not have it. Is it possible to leave the block and catch the error somewhere inside it. Or try a workaround by defining `window,checkoutConfig.quoteData` as an empty object when missing.

**Comment by vitaliyreznikov** [comment]
Agree with Daniel here. Let's check if we can put require() call into catch block and just swallow an error

**Comment by dumega** [comment]
@vitaliyreznikov @danac-gs Yes, that make sense, I will update the PR

**Comment by dumega** [comment]
@vitaliyreznikov @danac-gs PR is updated, now I use the require-specific errbacks of RequireJS tools to deal with any error if a module fails to load and log error details to console

**Review by vitaliyreznikov — APPROVED** [review]

**Pull request merged**
