### PR TITLE
M2P-222 Specify Bolt keys and Bolt signing secret as sensitive settings

### PR DESCRIPTION
**Pull request by johnmccombs1**
# Description
This PR is to add the bolt keys into the sensitive setting for security reasons.
See screenshot for testing here: https://prnt.sc/u6rv8n

Reference link: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/configuration/sensitive-and-environment-settings.html

Fixes: https://boltpay.atlassian.net/browse/M2P-222

#changelog M2P-222 Specify Bolt keys and Bolt signing secret as sensitive settings

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Review by vitaliyreznikov — COMMENTED** [review]
1. Is it Magento 2.1 compatible?
2. Publishable keys aren't sensetive ones, we show them in page source
3. If I understand correctly after this `config:set `will not work and we need use `config:sensitive:set`. Could you confirm? If so we need to change a lot of circleci scripts.

**Comment by vitaliyreznikov** [comment]
Magento 2.1 compatibility doesn't matter because we will support 2.3+ going forward.

**Review by danac-gs — APPROVED** [review]

**Comment by johnmccombs1** [comment]
@vitaliyreznikov 
**Is it Magento 2.1 compatible?**
=> Magento 2.1 is pretty old and our plugin doesn't support it, right? see here: https://prnt.sc/1799mez

**Publishable keys aren't sensetive ones, we show them in page source**
=> I'll ignore the publishable keys

**If I understand correctly after this config:set will not work and we need use config:sensitive:set. Could you confirm?
 If so we need to change a lot of circleci scripts.**
 => Yes, we need to use config:sensitive:set. Can you also tell me what circleci scripts that we need to change here?

**Comment by vitaliyreznikov** [comment]
@johnmccombs1 Please search for "payment/boltpay/api_key" over plugin code.

**Pull request closed without merging**
