### PR TITLE
ON-648 Bugfix: The Cart doesn't contain the xxxx item

### PR DESCRIPTION
**Pull request by dumega**
# Description
When transfer data from parent quote to the immutable quote ([code link](https://github.com/BoltApp/bolt-magento2/blob/2.18.1/Helper/Cart.php#L1105)), our plugin directly set the 'items' property with the data of parent quote ([code link](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/Quote/Model/Quote.php#L560)), as a result, when calling $immutableQuote->getItems();, actually it returns the items in parent quote instead of immutable quote, and eventually causes the exception __('The %1 Cart doesn\'t contain the %2 item.', $cartId, $itemId)([code link](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/Quote/Model/Quote/Item/CartItemPersister.php#L70))

Solution: Refer to M2 core code ([code link](https://github.com/magento/magento2/blob/fbfac3e51730abe2b79c6072544bc9742fcf7606/app/code/Magento/Quote/Model/QuoteRepository/LoadHandler.php#L46)), we can clone this property by $child->setItems($child->getAllVisibleItems());

Fixes: https://boltpay.atlassian.net/browse/ON-648

#changelog Bugfix: The Cart doesn't contain the xxxx item

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by vitaliyreznikov** [comment]
> when calling $immutableQuote->getItems();, actually it returns the items in parent quote instead of immutable quote

Do I understand correctly, we do not clone items right now? When we create an immutable quote we add "links" to the parent quote item?

**Comment by dumega** [comment]
@vitaliyreznikov yes, you are right. so in the foreach block, $cartId = $item->getQuoteId(); return the parent quote id, not the immutable quote id

**Comment by vitaliyreznikov** [comment]
What the steps to reproduce the issue? Something like if user changed parent quote but we didn't recreate the immutable one?

My concerns here: we create immutable quote very often, actually each time when we think that cart is changed. This is now plugin weakness because it works slow. If we add new SQL calls here, it will be even more slowly.

Can we move this code into the place where we decided to create bolt order from this immutable quote? After we check that cart from cache doesn't satisfy us?

**Comment by dumega** [comment]
@vitaliyreznikov do you mean here https://github.com/BoltApp/bolt-magento2/blob/master/Helper/Cart.php#L1734 ?

**Comment by vitaliyreznikov** [comment]
Here:
https://github.com/BoltApp/bolt-magento2/blob/358788072aa87cb9b106f4d1196290018f4f77af/Helper/Cart.php#L888

**Comment by dumega** [comment]
> Here:
> https://github.com/BoltApp/bolt-magento2/blob/358788072aa87cb9b106f4d1196290018f4f77af/Helper/Cart.php#L888

Please check the [bugsnag logs](https://app.bugsnag.com/bolt/magento-2/errors/603730d329bdd700170cc3ef?filters[event.since][0][type]=eq&filters[event.since][0][value]=1d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[metaData.META%20DATA.store_url][0][type]=eq&filters[metaData.META%20DATA.store_url][0][value]=https%3A%2F%2Fmigrate.andrewchristian.com%2F), the line you link I am afraid it is too late.

**Review by danac-gs — APPROVED** [review]
LGTM

**Comment by vitaliyreznikov** [comment]
@dumega How we can reproduce this?

**Comment by dumega** [comment]
@vitaliyreznikov For now I only can reproduce in the staging site of merchant andrewchristian, and it seems that the bug can be reproduced when the aheadworks/module-sarp2 and amasty/promo are both installed.

And when I output some debug info on my dev site, all the items of immutable quote fetched by getItems() actually belong to parent quote. You can verify this on your local as well.

**Review by vitaliyreznikov — APPROVED** [review]

**Pull request merged**
