### PR TITLE
M2P-467 Refactor V1 Endpoints

### PR DESCRIPTION
**Pull request by njfaries**
# Description
During work on V2 endpoints it was brought up that we should extract the handler behaviour so that instead of the V2 endpoint calling the V1 endpoint we have V1 and V2 both call the appropriate handler. This is a WIP commit to show my thought process and get feedback on the approach. Put simply, I am creating a new interface and implementation (currently called `OldApi`, name can be changed but just a placeholder for now) that will receive all the V1 endpoint hooks and call the appropriate handler. In practice it's quite similar to the universal API, the key difference being that the universal API has a single end point that routes to a variety of handlers, whereas this approach to V1 has many endpoints going through a single interface to reach many handlers.

For this PR I'm not touching the return types, there is a ticket to clean up sending response vs returning an interface but that is not part of this PR.

Fixes: https://boltpay.atlassian.net/browse/M2P-467

#changelog [WIP] M2P-467 Refactor V1 Endpoints

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by adentong** [comment]
I dunno, OldApiInterface is kind of a strange name, but then again I don't really have a better idea...

**Comment by njfaries** [comment]
> I dunno, OldApiInterface is kind of a strange name, but then again I don't really have a better idea...

Yeah, very open to suggestions on this one. Maybe `SplitApiInterface`?

**Comment by adentong** [comment]
What about just NonUniversalApiInterface?

**Comment by njfaries** [comment]
@danac-gs @vitaliyreznikov bumping this for review. Also votes on the name appreciated, I think I might just go with @adentong 's `NonUniversalApiInterface` suggestion if no one has a better idea

**Comment by vitaliyreznikov** [comment]
`NonUniversalApiInterface` works for me. Also please consider "LegacyApiInterface"

**Review by vitaliyreznikov — APPROVED** [review]

**Comment by njfaries** [comment]
> `NonUniversalApiInterface` works for me. Also please consider "LegacyApiInterface"

I like Legacy, I'll rename it and then merge

**Pull request merged**
