### PR TITLE
fix collision bug with EE PageBuilder module

### PR DESCRIPTION
**Pull request by danac-gs**
# Description
There's a collision bug with Magento\PageBuilder (EE only) module. Details in Asana task below.

Fixes: https://app.asana.com/0/941920570700290/1159330950508011/f

(Optional: Add a changelog by writing a comment after "#changelog" on the next line)

\#changelog Fix collision issue with Magento\PageBuilder in 2.3.4 EE

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by YevhenShBolt** [comment]
@matt-thomason , @danac-gs 
> Is this backwards compat. to 2.0.X?

If not we can easily add dependency through ObjectManager.

**Comment by danac-gs** [comment]
> Is this backwards compat. to 2.0.X?

It should be. Tested with 2.1.8, the oldest I had available. We used to use  imageHelper before imageBlock. Switching to imageBlock was a mistake. Mine.

**Comment by YevhenShBolt** [comment]
@matt-thomason , FYI
From Magento 
(https://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-11-open-source.html)
(https://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-11-commerce.html)
This release (Magento 2.2.11) marks the final supported software release for Magento version 2.2. Magento 2.2 will no longer receive security updates or product quality fixes now that its support window has expired.

**Comment by matt-thomason** [comment]
@YevhenShBolt We still support from 2.0 on docs.bolt.com. I'll create a task with Daniel Dresser to communicate us discontinuing support for 2.0 through 2.2 then.

**Comment by matt-thomason** [comment]
Task to update Bolt EOL on M2: https://app.asana.com/0/941920570700290/1159448272478769

**Comment by danac-gs** [comment]
@melvin0008 I will merge this but you should still be able to see the changes. If you find something that needs changing please let me know, we can do it in another PR.

**Pull request merged**
