### PR TITLE
M2P-576 Adds support for J2t Rewardpoints

### PR DESCRIPTION
**Pull request by dumega**
# Description
Adds support for J2t Rewardpoints

Fixes: https://boltpay.atlassian.net/browse/M2P-576

#changelog Adds support for J2t Rewardpoints

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by njfaries** [comment]
@dumega is this still a draft? or are you ready for it to be a full pull request?

**Comment by dumega** [comment]
@njfaries we still wait for the response (https://boltpay.atlassian.net/browse/EN-4664), so I keep this PR in draft if there is any update.

**Comment by vitaliyreznikov** [comment]
@dumega Do we still need this? This is the only draft we have now.

**Comment by dumega** [comment]
@vitaliyreznikov  @danac-gs  Please review when you get a chance. Thanks

**Review by vitaliyreznikov — APPROVED** [review]
LGTM

**Review by danac-gs — APPROVED** [review]

**Pull request merged**
