### PR TITLE
MX-1236 Postpone order->place() hook and do it when pending/processing hook received

### PR DESCRIPTION
**Pull request by vitaliyreznikov**
This PR works around issue around we trigger event sales_order_place_after when order just created and we don't know if transaction will be failed or not.

Event triggers in method order::place()
https://github.com/magento/magento2/blob/9e9703afdacac8c0ad098d7a492f3a9000c80199/app/code/Magento/Sales/Model/Order.php#L1185
Actually "place" means place payment.

So solution is to not call it when we created order. We can call it in pending/processing hook.

We had another protection around failed order: we don't set status "new" to order before hook received. But order status "new" is setting into order::place() so we can remove the appropriate code.

To call order::place() only once we rely to order status "bolt_pending". So we can have problem it 3party plugin decides to update status. But I don't think that it's the real issue.

Fixes: [MX-1236]

#changelog trigger event sales_order_place_after when we have payment

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

[MX-1236]: https://boltpay.atlassian.net/browse/MX-1236

### CODE REVIEW

**Comment by danac-gs** [comment]
@vitaliyreznikov I can not access https://boltpay.atlassian.net/browse/MX-1236 nor https://boltpay.atlassian.net/browse/EN-180

**Comment by vitaliyreznikov** [comment]
@danac-gs Moved to M2 project https://boltpay.atlassian.net/browse/M2P-94

**Comment by danac-gs** [comment]
@vitaliyreznikov @matt-thomason @njfaries 
I propose a different solution that takes into account the existing order flow
`pending_payment -> new -> processing`. 
It is in this PR: https://github.com/BoltApp/bolt-magento2/pull/746

**Comment by vitaliyreznikov** [comment]
Closing because we selected another approach https://github.com/BoltApp/bolt-magento2/pull/746

**Pull request closed without merging**
