### PR TITLE
M2P-498 - TaxJar support - force rounding to 2 decimal points fix

### PR DESCRIPTION
**Pull request by danac-gs**
# Description
Before collecting taxes and processing totals, TaxJar does not round the prices to 2 decimal places.  It overwrites the total rows and may change the subtotal if the percentage discount is applied to items (and / or shipping). This new values are different than initial Magento  calculation passed to Bolt and results in order error due to totals mismatch. 

Fixes: https://boltpay.atlassian.net/browse/M2P-498

#changelog M2P-498 - TaxJar support - force rounding to 2 decimal points fix

# Type of change

- [x] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [x] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Review by vitaliyreznikov — DISMISSED** [review]
LGTM. Please add couple of words why we need this as a comment

**Comment by danac-gs** [comment]
> LGTM. Please add couple of words why we need this as a comment

Done

**Review by vitaliyreznikov — APPROVED** [review]
LGTM. @danac-gs Could you please add a link to issue you created, as a comment?

**Comment by danac-gs** [comment]
> LGTM. @danac-gs Could you please add a link to issue you created, as a comment?

done

**Pull request merged**
