### PR TITLE
Add description field to the quote item collection.

### PR DESCRIPTION
**Pull request by YevhenShBolt**
# Description
Payment transactions processed via Stripe require a field "description" for level 3 processing. Now this field is missing in the quote item collection

Fixes: https://app.asana.com/0/941920570700290/1153065154514665/f

(Optional: Add a changelog by writing a comment after "#changelog" on the next line)

\#changelog

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by nirajjayantbolt** [comment]
Any way we can write unit tests for this? Might not be possible but just curious

**Comment by nirajjayantbolt** [comment]
@YevhenShBolt also can you explain to me what this is doing? I assume its adding description to the attributes of these items but where is the code that will actually send this information to Bolt when we create the order?

**Comment by isklyarenko** [comment]
> @YevhenShBolt also can you explain to me what this is doing? I assume its adding description to the attributes of these items but where is the code that will actually send this information to Bolt when we create the order?

@nirajjayantbolt such code was added before in Helper/Cart.php, line 1048, but it always returns null since the field "description" isn't in the collection

`$product['description'] = strip_tags($_product->getDescription());`

**Comment by nirajjayantbolt** [comment]
@isklyarenko thanks!

**Comment by danac-gs** [comment]
@YevhenShBolt 
After a second look I realize that we are loading the description from the underlying product object, not from the item itself. Would it be reasonable / safe to add another, `catalog_product`, group with the same attribute, like it is done in `vendor/magento/module-bundle/etc/catalog_attributes.xml`?

**Comment by nirajjayantbolt** [comment]
@isklyarenko once we merge this, how quickly can we get this to Lund?

**Comment by YevhenShBolt** [comment]
@danac-gs Can you clarify your question? It is not clear for me what you suggest.
>Would it be reasonable / safe to add another, catalog_product, group with the same attribute, like it is done in vendor/magento/module-bundle/etc/catalog_attributes.xml?

**Comment by danac-gs** [comment]
> @danac-gs Can you clarify your question? It is not clear for me what you suggest.
> 
> > Would it be reasonable / safe to add another, catalog_product, group with the same attribute, like it is done in vendor/magento/module-bundle/etc/catalog_attributes.xml?

Probably unnecessary safeguarding. I was thinking something like this:

```xml
<group name="catalog_product">
    <attribute name="description"/>
</group>
<group name="quote_item">
    <attribute name="description"/>
</group>
```
And perhaps even
```php
$product['description'] = strip_tags($_product->getDescription() ?: $item->getDescription());
```

**Comment by matt-thomason** [comment]
@YevhenShBolt @danac-gs Resurfacing this - are we going to go ahead with @danac-gs's suggestion?

**Comment by isklyarenko** [comment]
@matt-thomason  sorry for the delay here

@danac-gs When creating a cart item we only work with a quote item and don't use a catalog product directly for it (please see \Bolt\Boltpay\Helper\Cart::getCartItems). On the other hand, the product description can be large and we should avoid its loading everywhere until we don't need it.
Therefore I would prefer to keep loading of the description in the quote item only

**Comment by danac-gs** [comment]
@njfaries @matt-thomason @isklyarenko @YevhenShBolt can we merge this?

**Comment by YevhenShBolt** [comment]
i think yes

**Pull request merged**
