### PR TITLE
Discount calculation refactoring

### PR DESCRIPTION
**Pull request by garmashdev**
# Description
Refactored native discount calculation process.

Fixes: [(link ticket)](https://app.asana.com/0/1201931884901947/1202225720729002/f) . We have an issue in native code of discount calculation, which is described in the ticket abowe. When discount is more than subtotal we are sending to bolt data with not real discount applied but with rule full discount. In this case our discount amount is applying to shipment too which is incorrect. For example rule can have discount 5000$ and item price 20$, we are sending discount $5000 instead real discount applied 20$.  I've changed logic of this method(getSaleRuleDiscounts) to use default magento logic which is using in core collect totals method(Magento\SalesRule\Model\RulesApplier). In this case i'm able to have correct data of applied discounts per items and send those data to bolt by array: [ruleId => real discount applied].

#changelog Discount calculation refactoring

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 

- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my ticket link and provided a changelog message.

### CODE REVIEW

**Review by vitaliyreznikov — COMMENTED** [review]
@garmashdev Could you please add some explanation about your fix?

**Comment by garmashdev** [comment]
@vitaliyreznikov PR description updated.

**Review by dumega — COMMENTED** [review]
@garmashdev To fix this issue, you directly copy code from M2 core, right?
If this is for fixing specific bug of M2 core, I suggest we do it via plugin method to override [function getSaleRuleDiscounts](https://github.com/BoltApp/bolt-magento2/blob/2.25.1/Helper/Cart.php#L2880) and restrict the fix on specific M2 version only?
In this way, it does not effect M2 versions which already have fix and won't introduce new bug in our plugin.

**Comment by garmashdev** [comment]
@dumega hi, it is not magento core bug, the bug in our magento https://github.com/BoltApp/bolt-magento2/blob/2.25.1/Helper/Cart.php#L2880 method.  On legacy Magento 2.4.3 we have the same issue which was confirmed from QA team. I added there magento core calculation logic(not a copy, as composition after investigation core methods) from core classes. thanks.

**Comment by dumega** [comment]
> @dumega hi, it is not magento core bug, the bug in our magento https://github.com/BoltApp/bolt-magento2/blob/2.25.1/Helper/Cart.php#L2880 method. On legacy Magento 2.4.3 we have the same issue which was confirmed from QA team. I added there magento core calculation logic(not a copy, as composition after investigation core methods) from core classes. thanks.

But in the related ticket, it says this is caused by magento bug https://github.com/magento/magento2/issues/24422 , also I can not reproduce it in M2 2.4.3-p2 .

Do you have a screenshot of the settings of coupon?

**Comment by garmashdev** [comment]
@dumega yes:
fixed

**Review by dumega — CHANGES_REQUESTED** [review]
@garmashdev I run some test in my dev site with this PR, although it fixes the bug mentioned in the [ticket](https://app.asana.com/0/1201931884901947/1202225720729002/f), we face another issue happened before, your PR does not handle whole cart shipping discount properly. Please check the task https://app.asana.com/0/1124368832381302/1201663986351838/f for details.

Then could you dig into this issue again? Thanks

**Comment by garmashdev** [comment]
@dumega hi, after discussion with @mikeshutov-bolt we decided to add a new option to add this pr calculation logic for special cases : "Magento Native Discount Calculation" with off default value.
Снимок экрана 2022-05-27 в 13 11 17

**Pull request closed without merging**
