### PR TITLE
M2P-261 Code refactoring for 3rd-party module Mageplaza GiftCard

### PR DESCRIPTION
**Pull request by johnmccombs1**
# Description
Code refactoring for 3rd-party module Mageplaza GiftCard

Fixes: https://boltpay.atlassian.net/browse/M2P-261

#changelog M2P-261 Code refactoring for 3rd-party module Mageplaza GiftCard

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# For PR Reviewer 
- [ ] Reviewed unit tests to make sure we are using real components rather than mocks as much as possible?
- [ ] For any major change (observer, new Bolt feature, core Magento interaction) we must add a feature switch, did you verify this?

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Jira ticket link and provided a changelog message.

### CODE REVIEW

**Comment by vitaliyreznikov** [comment]
Please rebase PR onto master.

**Comment by johnmccombs1** [comment]
@vitaliyreznikov I've rebased the branch. Could you please re-check?

**Review by vitaliyreznikov — APPROVED** [review]

**Comment by vitaliyreznikov** [comment]
@dumega Ning could you please review this PR as well?

**Review by danac-gs — APPROVED** [review]

**Review by dumega — APPROVED** [review]
LGTM

**Pull request merged**
